#!/bin/bash

# Get a list of all accounts in the organization
accounts=$(aws organizations list-accounts --output json)

# Loop through each account
for account in $(echo "$accounts" | jq -r '.Accounts[].Id'); do
  # Switch to the current account using the --profile option
  export AWS_PROFILE="arn:aws:organizations::$account"

  # Get a list of all Fargate instances in the current account
  instances=$(aws ecs list-task-definitions --output json)

  # Print the task definition names
  echo "Fargate instances in account $account:"
  echo "$instances" | jq -r '.taskDefinitionArns[]'
done
